version: '3.8'

services:
    shopsmart-support:
        build: .
        container_name: shopsmart-support-app
        ports:
          - "8501:8501"
        env_file:
          - .env
        volumes:
          - ./vectorstore:/app/vectorstore
          - ./knowledge_base:/app/knowledge_base
        restart: unless-stopped

        healthcheck:
            test: ["CMD","curl","-f","http://localhost:8501/_stcore/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
               
